-- Table Assignments for Reception Seating
-- This table allows assigning tables to invitations or individual attendees

CREATE TABLE IF NOT EXISTS table_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id VARCHAR(50) NOT NULL,
    attendee_id BIGINT NULL, -- NULL means assignment applies to entire invitation
    table_number INTEGER NOT NULL,
    seat_number INTEGER NULL, -- Optional seat number within the table
    assigned_by BIGINT NULL, -- Admin user who made the assignment
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_table_assignments_invitation FOREIGN KEY (invitation_id) REFERENCES invitations(invitation_id) ON DELETE CASCADE,
    CONSTRAINT fk_table_assignments_attendee FOREIGN KEY (attendee_id) REFERENCES attendees(id) ON DELETE CASCADE,
    CONSTRAINT fk_table_assignments_admin FOREIGN KEY (assigned_by) REFERENCES admin_users(id) ON DELETE SET NULL,
    CONSTRAINT unique_invitation_attendee UNIQUE (invitation_id, attendee_id) -- Prevent duplicate assignments
);
CREATE INDEX IF NOT EXISTS idx_table_assignments_invitation_id ON table_assignments(invitation_id);
CREATE INDEX IF NOT EXISTS idx_table_assignments_attendee_id ON table_assignments(attendee_id);
CREATE INDEX IF NOT EXISTS idx_table_assignments_table_number ON table_assignments(table_number);